/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActCard: typeof import('./src/components/snowflake/ActCard.vue')['default']
    ActionTimeline: typeof import('./src/components/simulation/ActionTimeline.vue')['default']
    AgentStatePanel: typeof import('./src/components/simulation/AgentStatePanel.vue')['default']
    AnchorTimeline: typeof import('./src/components/world/AnchorTimeline.vue')['default']
    ApiFeedback: typeof import('./src/components/ApiFeedback.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/common/AppSidebar.vue')['default']
    ArbitrationResult: typeof import('./src/components/simulation/ArbitrationResult.vue')['default']
    ChapterCard: typeof import('./src/components/snowflake/ChapterCard.vue')['default']
    CharacterCard: typeof import('./src/components/snowflake/CharacterCard.vue')['default']
    ContentRenderer: typeof import('./src/components/editor/ContentRenderer.vue')['default']
    ConvergenceIndicator: typeof import('./src/components/simulation/ConvergenceIndicator.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    EntityList: typeof import('./src/components/world/EntityList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingOverlay: typeof import('./src/components/common/LoadingOverlay.vue')['default']
    LoglineSelector: typeof import('./src/components/snowflake/LoglineSelector.vue')['default']
    MarkdownPreview: typeof import('./src/components/editor/MarkdownPreview.vue')['default']
    RelationGraph: typeof import('./src/components/world/RelationGraph.vue')['default']
    RoundPlayer: typeof import('./src/components/simulation/RoundPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneCard: typeof import('./src/components/snowflake/SceneCard.vue')['default']
    SceneContextPanel: typeof import('./src/components/editor/SceneContextPanel.vue')['default']
    SceneEditor: typeof import('./src/components/editor/SceneEditor.vue')['default']
    SimulationLogs: typeof import('./src/components/editor/SimulationLogs.vue')['default']
    StateExtractPanel: typeof import('./src/components/StateExtractPanel.vue')['default']
    Step1Panel: typeof import('./src/components/snowflake/Step1Panel.vue')['default']
    Step2Panel: typeof import('./src/components/snowflake/Step2Panel.vue')['default']
    Step3Panel: typeof import('./src/components/snowflake/Step3Panel.vue')['default']
    Step4Panel: typeof import('./src/components/snowflake/Step4Panel.vue')['default']
    Step5Panel: typeof import('./src/components/snowflake/Step5Panel.vue')['default']
    Step6Panel: typeof import('./src/components/snowflake/Step6Panel.vue')['default']
    StepIndicator: typeof import('./src/components/snowflake/StepIndicator.vue')['default']
    SubplotPanel: typeof import('./src/components/world/SubplotPanel.vue')['default']
    VersionDiff: typeof import('./src/components/editor/VersionDiff.vue')['default']
  }
}
